CREATE TABLE IF NOT EXISTS USUARIOS (
    ID UUID NOT NULL,
    USERNAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    DATA_NASCIMENTO VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
);